# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BicepDocs < Formula
  desc "Command-line tool to generate documentation for Bicep templates"
  homepage "https://github.com/christosgalano/bicep-docs"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/christosgalano/bicep-docs/releases/download/v1.0.2/bicep-docs_darwin_arm64.tar.gz"
      sha256 "135a5c3e043373279802ebec8d60314f28a1159acb44f3bdc65bfd246cb59c07"

      def install
        bin.install "bicep-docs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/christosgalano/bicep-docs/releases/download/v1.0.2/bicep-docs_darwin_amd64.tar.gz"
      sha256 "7e6f7afa60fd1a3b35fed7993b527d7c18eeec450522f45f6e508ac1730e552e"

      def install
        bin.install "bicep-docs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/christosgalano/bicep-docs/releases/download/v1.0.2/bicep-docs_linux_arm.tar.gz"
      sha256 "e33ca911563c6609e4947409507cb5579259b6a612f42c89b0baa16f5894c677"

      def install
        bin.install "bicep-docs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/christosgalano/bicep-docs/releases/download/v1.0.2/bicep-docs_linux_arm64.tar.gz"
      sha256 "770e0e6a5474e47fbc0ec400db6b1716a339a79c416b80303bbbb6dc609a9004"

      def install
        bin.install "bicep-docs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/christosgalano/bicep-docs/releases/download/v1.0.2/bicep-docs_linux_amd64.tar.gz"
      sha256 "09917fff995158bca3a3b93b779c26c9d2364dac32e7c45198168116dbf0c2b9"

      def install
        bin.install "bicep-docs"
      end
    end
  end

  test do
    system "#{bin}/bicep-docs", "--help"
  end
end
