# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BicepDocs < Formula
  desc "Command-line tool to generate documentation for Bicep templates"
  homepage "https://github.com/christosgalano/bicep-docs"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/christosgalano/bicep-docs/releases/download/v1.2.0/bicep-docs_darwin_amd64.tar.gz"
      sha256 "a876474bd0ce4247e9fb670f87cca398e1a7c77f73cf1438e179546fb082260b"

      def install
        bin.install "bicep-docs"
      end
    end
    on_arm do
      url "https://github.com/christosgalano/bicep-docs/releases/download/v1.2.0/bicep-docs_darwin_arm64.tar.gz"
      sha256 "ad34e2f683b35b3c3583ccc91f55a9fd1edca2c98ddbdf4587bd9223001dbdb0"

      def install
        bin.install "bicep-docs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/christosgalano/bicep-docs/releases/download/v1.2.0/bicep-docs_linux_amd64.tar.gz"
        sha256 "db3936fc42a1b1cdd2b56407245cb57651fa77328a2a05a84468ba023ad4144b"

        def install
          bin.install "bicep-docs"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/christosgalano/bicep-docs/releases/download/v1.2.0/bicep-docs_linux_arm.tar.gz"
        sha256 "7bf366cde08328184f5e4ce7fca9442cd82b10e27b2d58dd9ca6bab6234df3ae"

        def install
          bin.install "bicep-docs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/christosgalano/bicep-docs/releases/download/v1.2.0/bicep-docs_linux_arm64.tar.gz"
        sha256 "a330043e1c152700a191471204634ff625e055d746be124fd2737683e675d98e"

        def install
          bin.install "bicep-docs"
        end
      end
    end
  end

  test do
    system "#{bin}/bicep-docs", "--help"
  end
end
