# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bruh < Formula
  desc "Command-line tool for scanning and updating the API version of Azure resources in Bicep files"
  homepage "https://github.com/christosgalano/bruh"
  version "1.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_darwin_arm64.tar.gz"
      sha256 "9bf5e0981ece910a73057d44688f3327cddc56efc51bde0550956f997cb02383"

      def install
        bin.install "bruh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_darwin_amd64.tar.gz"
      sha256 "80b4d9e22fcf1d85aa47e6d0c486011c7ab442de73bf20df85cfe92b46cb24e7"

      def install
        bin.install "bruh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_linux_arm.tar.gz"
      sha256 "c20a81149d25d539483e3c7f5639cd4b5c94ef588d692f24e55f5a3fd7107c25"

      def install
        bin.install "bruh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_linux_amd64.tar.gz"
      sha256 "faebccb4e6ec13d0d7d6f464b7a36c9c83e7080513f6ea7c5dd74e7543debb9c"

      def install
        bin.install "bruh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_linux_arm64.tar.gz"
      sha256 "4b2c74c48caf8e6e872385f00a3e37de121d15f3057617df73194a34717cd185"

      def install
        bin.install "bruh"
      end
    end
  end

  test do
    system "#{bin}/bruh", "--help"
  end
end
