# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bruh < Formula
  desc "Command-line tool for scanning and updating the API version of Azure resources in Bicep files"
  homepage "https://github.com/christosgalano/bruh"
  version "1.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_darwin_amd64.tar.gz"
      sha256 "90b2a7f09f30c423eab006d51a9ab1956a13354d98f86f1bd30ac513cca03e1f"

      def install
        bin.install "bruh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_darwin_arm64.tar.gz"
      sha256 "227d3d00fcae954cd888a733aa48ff47ea36a97558a70065d7f06bfa576b87fe"

      def install
        bin.install "bruh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_linux_amd64.tar.gz"
      sha256 "67caef01b4a7e259686fb2134cf26db8fe63fe39e9879dacd00b61c7ae281429"

      def install
        bin.install "bruh"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_linux_arm.tar.gz"
      sha256 "517b3f7757e0fb310fb033fb057fc31ad5c7f23eada85a9b6a57bce773a433de"

      def install
        bin.install "bruh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_linux_arm64.tar.gz"
      sha256 "1ba41fa143e4e352416c00c30fad9dbc4ceef1f790d336ea38c432f7e2c6bd41"

      def install
        bin.install "bruh"
      end
    end
  end

  test do
    system "#{bin}/bruh", "--help"
  end
end
