# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeleteGhWorkflowRuns < Formula
  desc "Command-line tool to generate documentation for Bicep templates"
  homepage "https://github.com/christosgalano/delete-gh-workflow-runs"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/christosgalano/delete-gh-workflow-runs/releases/download/v1.0.0/delete-gh-workflow-runs_darwin_amd64.tar.gz"
      sha256 "c0431fd5b1d7bb9721771341a2463876b49f6beb64383d3f195a26fe0e1a7041"

      def install
        bin.install "delete-gh-workflow-runs"
      end
    end
    on_arm do
      url "https://github.com/christosgalano/delete-gh-workflow-runs/releases/download/v1.0.0/delete-gh-workflow-runs_darwin_arm64.tar.gz"
      sha256 "a23839355e9fcb852acfbaf069db25f46e27ebde6fb604f2175346518abe1be8"

      def install
        bin.install "delete-gh-workflow-runs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/christosgalano/delete-gh-workflow-runs/releases/download/v1.0.0/delete-gh-workflow-runs_linux_amd64.tar.gz"
        sha256 "270b308433b299ae59decc84d1b97631295f5aa0f9fa02ced91dfaa4f9abcb71"

        def install
          bin.install "delete-gh-workflow-runs"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/christosgalano/delete-gh-workflow-runs/releases/download/v1.0.0/delete-gh-workflow-runs_linux_arm.tar.gz"
        sha256 "d688c8d4c9223079761ffc16f32f9ace3af79c17de81ba434bc76afb3a6bcf08"

        def install
          bin.install "delete-gh-workflow-runs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/christosgalano/delete-gh-workflow-runs/releases/download/v1.0.0/delete-gh-workflow-runs_linux_arm64.tar.gz"
        sha256 "8f92509c8b80150cbf36e6952b916be2cad381cb7d6d170b0cf9a314917426db"

        def install
          bin.install "delete-gh-workflow-runs"
        end
      end
    end
  end

  test do
    system "#{bin}/delete-gh-workflow-runs", "--help"
  end
end
