# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeleteGhWorkflowRuns < Formula
  desc "Command-line tool to generate documentation for Bicep templates"
  homepage "https://github.com/christosgalano/delete-gh-workflow-runs"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/christosgalano/delete-gh-workflow-runs/releases/download/v1.0.0/delete-gh-workflow-runs_darwin_amd64.tar.gz"
      sha256 "519bdbc375c147a3ddc94790df99ffe73087cc7f70f3509c9576f0080baaa1d0"

      def install
        bin.install "delete-gh-workflow-runs"
      end
    end
    on_arm do
      url "https://github.com/christosgalano/delete-gh-workflow-runs/releases/download/v1.0.0/delete-gh-workflow-runs_darwin_arm64.tar.gz"
      sha256 "6e1a61449592906c91c07115770483cbfa8e40d1c09fdf2dce143cceeef8b8aa"

      def install
        bin.install "delete-gh-workflow-runs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/christosgalano/delete-gh-workflow-runs/releases/download/v1.0.0/delete-gh-workflow-runs_linux_amd64.tar.gz"
        sha256 "fa54e84b0bab4022c9889a4fcc798d360d18e33d4289adcded8081430bb9d9f0"

        def install
          bin.install "delete-gh-workflow-runs"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/christosgalano/delete-gh-workflow-runs/releases/download/v1.0.0/delete-gh-workflow-runs_linux_arm.tar.gz"
        sha256 "9bad80bd9b69351d65edd414d086954146890663f36eb61d217f7f9da34a62c5"

        def install
          bin.install "delete-gh-workflow-runs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/christosgalano/delete-gh-workflow-runs/releases/download/v1.0.0/delete-gh-workflow-runs_linux_arm64.tar.gz"
        sha256 "679430ffee0d75e90621857df67fbab2e7aadadd1b26a487569a7e12e4fa6d31"

        def install
          bin.install "delete-gh-workflow-runs"
        end
      end
    end
  end

  test do
    system "#{bin}/delete-gh-workflow-runs", "--help"
  end
end
